version: '3'

services:
  db_breiv:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=db_breiv
    ports:
      - "3306:3306"

  app:
    image: openjdk:8
    restart: always
    working_dir: /app
    volumes:
      - ../application/build/libs:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: java -jar breiv-1.0.0-REALEASE.jar
    depends_on:
      - db_breiv
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=prod
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=db_breiv
      - DATABASE_PORT=3306
      - DATABASE_HOST=db_breiv